"""Required file and marker checks for isONclust3 release preflight."""

from __future__ import annotations

from pathlib import Path

REQUIRED_FILES = [
    "AGENTS.md",
    "BENCHMARK_ACCEPTANCE.md",
    "BLOCKERS.md",
    "Dockerfile",
    ".gitignore",
    "MILESTONES.md",
    "OPTIMIZATION_EVIDENCE.md",
    "OUTPUT_CONTRACTS.md",
    "PERFORMANCE_DEEP_DIVE.md",
    "README.md",
    "RELEASE_CHECKLIST.md",
    "RELEASE_NOTES.md",
    "TODO.md",
    "scripts/check-output-contract-fixtures.sh",
    "scripts/check-docker-toy-benchmarks.sh",
    "scripts/run-local-profiling.sh",
    "scripts/run-gb10-benchmark.sh",
    "scripts/preflight_artifacts.py",
    "scripts/preflight_benchmark_schema.py",
    "scripts/preflight_ci.py",
    "scripts/preflight_gb10_runner.py",
    "scripts/preflight_governance.py",
    "scripts/preflight_output_contracts.py",
    "scripts/preflight_optimization_evidence.py",
    "scripts/preflight_release_checklist.py",
    "scripts/preflight_required_files.py",
    "fixtures/output-contracts/final-clusters-register.json",
    "schemas/benchmark-fixture.schema.json",
    "schemas/output-contract-register.schema.json",
    "docs/requirements.txt",
    "docs/conf.py",
    "docs/index.rst",
    "docs/project-governance.rst",
    "docs/release-readiness.rst",
]

REQUIRED_TEXT = {
    "AGENTS.md": [
        "Maintain semantic versioning",
        "GB10 benchmark evidence",
        "Do not commit raw sequencing data",
        "waiver does not claim accepted producer evidence",
        "`newONform` checksum readiness",
        "Sphinx build",
        "Python virtual environments/cache artifacts",
        "## Documentation Rules",
        "Sphinx governance and release-readiness documentation",
        "sphinx-build -W -b html docs target/sphinx-html",
    ],
    ".gitignore": [
        "docs/_build/",
        ".venv/",
        "benchmark-artifacts/",
        "benchmark-output/",
        "gb10-output/",
        "reports/",
        "gb10-reports/",
    ],
    "BENCHMARK_ACCEPTANCE.md": [
        "final_clusters.tsv",
        "Container image ID or digest",
        "blocked_pending_data",
        "Waived producer gaps remain scoped release limitations",
        "must not be",
        "reported as `accepted_contract` or `accepted_calibration`",
        "Waived medium or Phanerognostikon producer gaps do not claim accepted GB10",
    ],
    "BLOCKERS.md": [
        "ISOCLUST-BLOCK-001",
        "ISOCLUST-BLOCK-002",
        "ISOCLUST-BLOCK-003",
        "ISOCLUST-BLOCK-004",
        "## Waiver Rules",
        "Waivers must name the blocker ID, affected workload, evidence available,",
        "downstream `newONform` impact, and expiry condition.",
        "does not claim accepted GB10 producer",
        "downstream `newONform` release train must list active",
    ],
    "MILESTONES.md": [
        "Dockerized GB10 Benchmarking",
        "Status: active. Dockerfile, toy ONT/PacBio benchmark manifests",
        "scripts/run-gb10-benchmark.sh",
        "ISOCLUST-BLOCK-001",
        "ISOCLUST-BLOCK-002",
    ],
    "OPTIMIZATION_EVIDENCE.md": [
        "Raw local reports must not be committed",
        "scripts/run-local-profiling.sh --case all --include-fastq-output --include-post-cluster --include-gff",
        "ISOCLUST-BLOCK-001",
        "ISOCLUST-BLOCK-003",
    ],
    "OUTPUT_CONTRACTS.md": [
        "<outfolder>/clustering/final_clusters.tsv",
        "fixtures/output-contracts/final-clusters-register.json",
        "schemas/output-contract-register.schema.json",
    ],
    "README.md": [
        "Release And Benchmark Evidence",
        "scripts/release-preflight.py --expected-version 0.3.0",
        "python -m pip install -r docs/requirements.txt",
        "sphinx-build -W -b html docs target/sphinx-html",
        "Waivers must stay visible as scoped release limitations",
        "do not claim accepted GB10 producer evidence",
        "generated `final_clusters.tsv` checksum",
        "scripts/check-docker-toy-benchmarks.sh",
        "scripts/run-local-profiling.sh --output-dir target/local-profile",
    ],
    "PERFORMANCE_DEEP_DIVE.md": [
        "local-profiling",
        "Ranked Facets",
        "Seed extraction and filtering",
        "Do not mark GB10 blockers resolved",
    ],
    "RELEASE_CHECKLIST.md": [
        "scripts/release-preflight.py --expected-version",
        "scripts/run-local-profiling.sh --case all --include-fastq-output --include-post-cluster --include-gff",
        "sphinx-build -W -b html docs target/sphinx-html",
        "GB10 runner checksum-handoff report",
        "explicitly waived without claiming accepted producer",
        "Update `newONform` submodule, generated-input registers, release notes,",
        "blockers, and Sphinx documentation in the same release train.",
    ],
    "RELEASE_NOTES.md": [
        "isONclust3 0.3.0-rc Planning Draft",
        "## Intended Scope",
        "Preserved `final_clusters.tsv` handoff contract",
        "Dockerized benchmark runner",
        "Sphinx documentation build markers",
        "## Evidence Required Before RC Acceptance",
        "Accepted GB10 benchmark reports",
        "generated `final_clusters.tsv` checksums",
        "Matching `newONform` submodule",
        "## Known Limits",
        "ISOCLUST-BLOCK-001",
        "ISOCLUST-BLOCK-002",
        "ISOCLUST-BLOCK-003",
        "## Operator Notes",
        "Waivers must stay visible as scoped release limitations",
        "not claim accepted GB10 producer evidence",
        "generated `final_clusters.tsv`",
        "Do not tag a release candidate from this draft alone.",
    ],
    "TODO.md": [
        "Dockerized GB10 Evidence",
        "local profiling harness",
        "Profile seed generation and minimizer/syncmer extraction",
        "Add benchmark evidence before and after every algorithmic optimization",
        "Record accepted GB10 benchmark reports",
        "Expose generated `final_clusters.tsv` checksums",
        "Keep `newONform` generated-input registers aligned",
        "Gate benchmark manifest readability and object root.",
        "Gate benchmark manifest duplicate file roles.",
        "Gate benchmark manifest duplicate file paths.",
        "Gate benchmark manifest schema path markers.",
        "Gate benchmark manifest schema contract markers.",
        "Gate benchmark manifest schema structural constraints.",
        "Gate benchmark manifest schema root key ordering.",
        "Gate benchmark manifest schema nested type policy.",
        "Gate benchmark manifest schema non-empty string policy.",
        "Gate benchmark manifest schema property ordering.",
        "Gate benchmark manifest schema additionalProperties policy.",
        "Gate benchmark manifest schema nested required field ordering.",
        "Gate benchmark manifest keys against the benchmark schema.",
        "Gate benchmark manifest checksum keys against the benchmark schema.",
        "Gate benchmark manifest key ordering against the benchmark schema.",
        "Gate GB10 runner report fields for generated `final_clusters.tsv`",
        "Gate release-checklist downstream handoff artifact markers.",
        "Gate blocker waiver rules for upstream producer evidence.",
        "Gate Sphinx waiver-boundary release-readiness markers.",
        "Gate Sphinx index waiver-scope status markers.",
        "Gate README waiver-scope release evidence markers.",
        "Gate release-note waiver-scope operator markers.",
        "Gate benchmark acceptance waiver-scope status markers.",
        "Gate Sphinx index generated-checksum waiver-scope markers.",
        "Gate release-checklist waiver-scope evidence markers.",
        "Gate AGENTS compatibility-waiver evidence markers.",
        "Gate expanded tracked-artifact hygiene markers.",
        "Gate .gitignore generated-artifact markers.",
        "Split tracked-artifact hygiene into a focused preflight module.",
        "Gate a machine-readable tiny `final_clusters.tsv` output-contract",
        "Gate the output-contract register schema.",
        "Gate output-contract schema entry constraints.",
        "Gate output-contract register paths as relative and non-escaping.",
        "Gate output-contract schema path patterns.",
        "Gate output-contract register entry ordering.",
        "Gate output-contract schema entry count.",
        "Gate output-contract schema exact entry count.",
        "Gate output-contract schema scalar entry constraints.",
        "Gate output-contract schema property types.",
        "Gate output-contract schema required field ordering.",
        "Gate output-contract schema property ordering.",
        "Gate output-contract schema catalog title.",
        "Gate output-contract schema entry ID enum.",
        "Gate output-contract schema unique entry rows.",
        "Gate output-contract schema definition keys.",
        "Gate output-contract schema root property types.",
        "Gate output-contract schema readability and object root.",
        "Gate output-contract register root key ordering.",
        "Gate output-contract register entry key ordering.",
        "Gate output-contract register readability and object root.",
    ],
    "schemas/benchmark-fixture.schema.json": [
        "isONclust3 benchmark fixture manifest",
        "isonclust3-benchmark-fixture",
        "benchmark_tier",
        "platform_targets",
        "isonclust3:gb10",
        "blocked_pending_data",
        "profiling_plan",
        "downstream_handoff",
        "generated_input_id",
        "NOF-BLOCK-006",
        "expected-final-clusters",
        "^[0-9a-f]{64}$",
    ],
    "docs/index.rst": [
        "isONclust3 Maintained Fork",
        "Current Status",
        "accepted GB10 reports",
        "generated ``final_clusters.tsv`` producer checksums",
        "Any explicit waiver must stay visible as a scoped",
        "must not claim accepted GB10 producer evidence",
        "generated ``final_clusters.tsv`` checksum readiness",
        "project-governance",
        "release-readiness",
    ],
    "docs/project-governance.rst": [
        "Project Governance",
        ".. literalinclude:: ../AGENTS.md",
        ".. literalinclude:: ../MILESTONES.md",
        ".. literalinclude:: ../TODO.md",
        ".. literalinclude:: ../BLOCKERS.md",
        ".. literalinclude:: ../BENCHMARK_ACCEPTANCE.md",
        ".. literalinclude:: ../RELEASE_CHECKLIST.md",
        ".. literalinclude:: ../RELEASE_NOTES.md",
    ],
    "docs/release-readiness.rst": [
        "Release Readiness",
        "Minimum Local Checks",
        "Current High-Priority Blockers",
        "ISOCLUST-BLOCK-001",
        "ISOCLUST-BLOCK-002",
        "ISOCLUST-BLOCK-003",
        "Waivers must name the blocker, workload, available evidence",
        "does not claim accepted GB10 producer evidence",
        "``final_clusters.tsv`` checksum readiness",
        "sphinx-build -W -b html docs target/sphinx-html",
        "Downstream Handoff",
        "external/isONclust3",
    ],
    "scripts/preflight_gb10_runner.py": [
        "GB10 runner contract checks",
        "REQUIRED_RUNNER_MARKERS",
        "REQUIRED_TSV_FIELDS",
        "final_clusters_sha256",
        "accepted_contract",
    ],
}


def validate_required_files(repo: Path) -> list[str]:
    errors: list[str] = []
    for relative in REQUIRED_FILES:
        path = repo / relative
        if not path.is_file():
            errors.append(f"missing required file: {relative}")
    for relative, markers in REQUIRED_TEXT.items():
        path = repo / relative
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        for marker in markers:
            if marker not in text:
                errors.append(f"{relative} missing marker: {marker}")
    return errors
